# Generated by Django 4.2.6 on 2023-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0002_alter_receita_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='image',
            field=models.ImageField(null=True, upload_to='imagens/'),
        ),
    ]
